"""Built-in device templates for Heat Pump Configurator."""

# ---------------------------------------------------------------------------
# Generic Heat Pump template (based on real-world iThermPump / Midea registers)
# Covers: sensors, bitmask binary_sensors, select entities, number setpoints
# ---------------------------------------------------------------------------

TEMPLATE_GENERIC_HEATPUMP = {
    "name": "Generic Heat Pump",
    "connection_type": "esphome",
    "scan_interval": 5,
    "connection_params": {
        "platform": "ESP32",
        "board": "esp32dev",
        "tx_pin": "GPIO15",
        "rx_pin": "GPIO14",
        "baudrate": 9600,
        "slave": 1,
        "parity": "NONE",
        "stop_bits": 1,
    },
    "registers": [
        # ── Internal shadow register ────────────────────────────────────────
        {
            "name": "senzor_2000",
            "friendly_name": "Register 0x2000 (internal)",
            "register": 0x2000,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "sensor",
            "internal": True,
        },
        # ── Temperature sensors ─────────────────────────────────────────────
        {
            "name": "vstupna_teplota_vody",
            "friendly_name": "Vstupná tep. vody",
            "register": 0x000E,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "sensor",
            "unit": "°C",
            "device_class": "temperature",
            "state_class": "measurement",
            "accuracy_decimals": 0,
            "icon": "mdi:thermometer",
            "custom_filters": "- multiply: 0.1",
        },
        {
            "name": "aktualna_teplota_tuv",
            "friendly_name": "Aktuálna tep. TUV",
            "register": 0x000F,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "sensor",
            "unit": "°C",
            "device_class": "temperature",
            "state_class": "measurement",
            "accuracy_decimals": 0,
            "icon": "mdi:thermometer",
            "custom_filters": "- multiply: 0.1",
        },
        {
            "name": "vystupna_teplota_vody",
            "friendly_name": "Výstupná tep. vody",
            "register": 0x0012,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "sensor",
            "unit": "°C",
            "device_class": "temperature",
            "state_class": "measurement",
            "accuracy_decimals": 0,
            "icon": "mdi:thermometer",
            "custom_filters": "- multiply: 0.1",
        },
        {
            "name": "vonkajsia_teplota",
            "friendly_name": "Vonkajšia teplota",
            "register": 0x0001,
            "register_type": "holding",
            "data_type": "int16",
            "entity_type": "sensor",
            "unit": "°C",
            "device_class": "temperature",
            "state_class": "measurement",
            "accuracy_decimals": 0,
            "icon": "mdi:thermometer",
            "custom_filters": "- multiply: 0.1",
        },
        # ── Power / COP ─────────────────────────────────────────────────────
        {
            "name": "cop",
            "friendly_name": "COP",
            "register": 0x0037,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "sensor",
            "unit": "cop",
            "accuracy_decimals": 1,
            "custom_filters": "- multiply: 0.1\n- lambda: |-\n    if (x < 0.1) return 0.0f;\n    if (x > 14.0) return 15.0f;\n    return x;",
        },
        {
            "name": "senzor_0036",
            "friendly_name": "Vykurovací výkon",
            "register": 0x0036,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "sensor",
            "unit": "kW",
            "device_class": "power",
            "state_class": "measurement",
            "accuracy_decimals": 1,
            "custom_filters": "- lambda: |-\n    if (!id(kompresor).state) {\n      return 0.0;\n    }\n    return x * 0.1;",
        },
        {
            "name": "aktualna_spotreba_tepelka",
            "friendly_name": "Aktuálna spotreba",
            "register": 0x0038,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "sensor",
            "unit": "kW",
            "device_class": "power",
            "state_class": "measurement",
            "accuracy_decimals": 2,
            "custom_filters": "- multiply: 0.1",
        },
        # ── Integration sensor (runtime energy tracking) ────────────────────
        {
            "name": "energy_total_tepelka",
            "friendly_name": "Celková spotreba",
            "entity_type": "integration_sensor",
            "integration_source": "aktualna_spotreba_tepelka",
            "integration_time_unit": "h",
            "unit": "kWh",
            "device_class": "energy",
            "state_class": "total_increasing",
            "accuracy_decimals": 2,
            "restore": True,
        },
        {
            "name": "kompresor_runtime_h",
            "friendly_name": "Kompresor - celkový čas behu",
            "entity_type": "integration_sensor",
            "integration_source": "kompresor_bezi_10",
            "integration_time_unit": "h",
            "unit": "h",
            "state_class": "total_increasing",
            "accuracy_decimals": 3,
            "restore": True,
        },
        # ── Binary sensors with bitmask ─────────────────────────────────────
        {
            "name": "kompresor",
            "friendly_name": "Kompresor",
            "register": 0x0004,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "binary_sensor",
            "bitmask": "0x0001",
            "icon": "mdi:engine",
        },
        {
            "name": "ventilator",
            "friendly_name": "Ventilátor",
            "register": 0x0004,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "binary_sensor",
            "bitmask": "0x0020",
            "icon": "mdi:fan",
        },
        {
            "name": "stvorcestny_ventil",
            "friendly_name": "Štvorcestný ventil",
            "register": 0x0004,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "binary_sensor",
            "bitmask": "0x0040",
            "icon": "mdi:valve",
        },
        {
            "name": "obehove_cerpadlo",
            "friendly_name": "Obehové čerpadlo",
            "register": 0x0006,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "binary_sensor",
            "bitmask": "0x0004",
            "icon": "mdi:pump",
        },
        {
            "name": "elektricky_ohrev",
            "friendly_name": "Elektrický ohrev",
            "register": 0x0005,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "binary_sensor",
            "bitmask": "0x0020",
            "icon": "mdi:radiator",
        },
        {
            "name": "ohrev_zasobnika_tuv",
            "friendly_name": "Ohrev zásobníka TUV",
            "register": 0x0005,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "binary_sensor",
            "bitmask": "0x0080",
            "icon": "mdi:water-boiler",
        },
        # ── Bitmask sensor → text sensor pairs ─────────────────────────────
        {
            "name": "kompresor_bezi_10",
            "friendly_name": "Kompresor beží (interný)",
            "register": 0x0004,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "bitmask_sensor",
            "bitmask": "0x0001",
            "internal": True,
            "text_sensor_id": "kompresor_stav_text",
            "text_sensor_name": "Kompresor - stav",
            "true_text": "Beží",
            "false_text": "Stojí",
            "icon": "mdi:engine",
        },
        # ── Select entities ─────────────────────────────────────────────────
        {
            "name": "tepelne_cerpadlo",
            "friendly_name": "Tepelné čerpadlo",
            "register": 0x2000,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "select",
            "options_map": '{"Vypnuté": 0, "Zapnuté": 1}',
            "select_lambda": 'uint16_t reg_value = static_cast<uint16_t>(id(senzor_2000).state);\nreturn (reg_value & 0x01) != 0 ? std::string("Zapnuté") : std::string("Vypnuté");',
            "select_write_lambda": 'uint16_t unmodified = static_cast<uint16_t>(id(senzor_2000).state);\nuint16_t modified;\nif (x == "Zapnuté") { modified = unmodified | 0x01; } else { modified = unmodified & ~0x01; }\nreturn modified;',
        },
        {
            "name": "rezim_chodu",
            "friendly_name": "Režim chodu",
            "register": 0x2002,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "select",
            "options_map": '{"TUV": 0, "Kúrenie": 1, "Chladenie": 2, "TUV + Kúrenie": 3, "TUV + Chladenie": 4}',
        },
        {
            "name": "frekvencny_rezim_select",
            "friendly_name": "Frekvenčný režim",
            "register": 0x2000,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "select",
            "options_map": '{"Smart režim": 0, "Výkonný režim": 64, "Tichý režim": 128}',
            "select_lambda": 'uint16_t reg_value = static_cast<uint16_t>(id(senzor_2000).state);\nif ((reg_value & 0xC0) == 0) { return std::string("Smart režim"); }\nelse if ((reg_value & 0xC0) == 64) { return std::string("Výkonný režim"); }\nelse if ((reg_value & 0xC0) == 128) { return std::string("Tichý režim"); }\nreturn std::string("Neznámy režim");',
            "select_write_lambda": 'uint16_t unmodified = static_cast<uint16_t>(id(senzor_2000).state);\nuint16_t modified;\nif (x == "Smart režim") { modified = unmodified & ~0xC0; }\nelse if (x == "Výkonný režim") { modified = (unmodified & ~0xC0) | 64; }\nelse if (x == "Tichý režim") { modified = (unmodified & ~0xC0) | 128; }\nelse { modified = unmodified; }\nreturn modified;',
        },
        {
            "name": "dezinfekcie_tuv",
            "friendly_name": "Dezinfekcia TUV",
            "register": 0x2014,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "select",
            "options_map": '{"Vypnuté": 0, "Čo 5 dní": 5, "Čo 10 dní": 10, "Čo 15 dní": 15, "Čo 20 dní": 20, "Čo 25 dní": 25}',
        },
        # ── Number setpoints ────────────────────────────────────────────────
        {
            "name": "teplota_okolia_pre_spustenie_pridavneho_kurenia",
            "friendly_name": "Tep. okolia pre spus. príd. kúrenia",
            "register": 0x201B,
            "register_type": "holding",
            "data_type": "int16",
            "entity_type": "number",
            "unit": "°C",
            "min": -20,
            "max": 10,
            "step": 2,
            "device_class": "temperature",
            "icon": "mdi:thermometer",
        },
        {
            "name": "cielova_teplota_tuv",
            "friendly_name": "Cieľová teplota TUV",
            "register": 0x2006,
            "register_type": "holding",
            "data_type": "uint16",
            "entity_type": "number",
            "unit": "°C",
            "min": 30,
            "max": 80,
            "step": 1,
            "device_class": "temperature",
            "scale": 1.0,
            "icon": "mdi:thermometer",
        },
        # ── Text sensors (template) ─────────────────────────────────────────
        {
            "name": "kompresor_celkovy_cas_text",
            "friendly_name": "Kompresor - celkový čas (HH:MM)",
            "entity_type": "text_sensor",
            "text_sensor_template": True,
            "update_interval": "10s",
            "lambda": 'int total_min = (int) floor(id(kompresor_runtime_h).state * 60.0f + 0.5f);\nint hh = total_min / 60;\nint mm = total_min % 60;\nchar buf[16];\nsnprintf(buf, sizeof(buf), "%d:%02d", hh, mm);\nreturn std::string(buf);',
        },
    ],
    "globals": [
        {"id": "hodnota_2000", "type": "int", "initial_value": "0"},
        {"id": "ulozena_celkova_spotreba", "type": "float", "restore_value": True},
    ],
    "extras": {
        "modbus_send_wait_time": "500ms",
        "esp_status_sensor": True,
        "esp_ip_sensor": True,
        "restart_switch": True,
    },
}


def get_template(template_name: str) -> dict:
    """Return a copy of the named template."""
    import copy
    templates = {
        "generic_heatpump": TEMPLATE_GENERIC_HEATPUMP,
    }
    tpl = templates.get(template_name)
    if tpl is None:
        return {}
    return copy.deepcopy(tpl)
